REGIONS_MAP = {
    "acre": "Norte",
    "amazonas": "Norte",
    "roraima": "Norte",
    "rondônia": "Norte",
    "pará": "Norte",
    "amapá": "Norte",
    "tocantins": "Norte",
    "maranhão": "Nordeste",
    "piauí": "Nordeste",
    "ceará": "Nordeste",
    "rio grande do norte": "Nordeste",
    "paraíba": "Nordeste",
    "pernambuco": "Nordeste",
    "alagoas": "Nordeste",
    "sergipe": "Nordeste",
    "bahia": "Nordeste",
    "mato grosso": "Centro-Oeste",
    "mato grosso do Sul": "Centro-Oeste",
    "goiás": "Centro-Oeste",
    "distrito federal": "Centro-Oeste",
    "minas gerais": "Sudeste",
    "espírito santo": "Sudeste",
    "rio de janeiro": "Sudeste",
    "são paulo": "Sudeste",
    "paraná": "Sul",
    "rio grande do sul": "Sul",
    "santa catarina": "Sul"
}
